#!/usr/bin/env python

import sys, argparse
from run_sim import run_sim, run_sims_range


import sys, argparse
from run_sim import run_sim

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--clientThreadsPerHost", type=str, default="1",
        help="The number of single threaded client processes to run on each host")
    parser.add_argument("--serverThreadsPerHost", type=str, default="1",
        help="The number of server threads to run on each host")
    parser.add_argument("--serverProcessingTime", type=str, default="1",
        help="The number of work units for the server threads to perform after receiving a message")
    parser.add_argument("--serverNetLoad", type=str, default="1",
        help="The number of the network messages for the server threads to send to a different server after receiving a message")
    parser.add_argument("--clientHPReqRate", type=str, default="1",
        help="The maximum rate of the high priority messages. Note: The actual rate will depend on the HP request latency")
    parser.add_argument("--clientLPReqRate", type=str, default="1",
        help="The maximum rate of the low priority messages. Note: The actual rate will depend on the HP request latency")
    parser.add_argument("--clientReqGrpSize", type=str, default="100",
        help="The size of the request group for which a measurement will be taken")
    parser.add_argument("--coresForHPThreads", type=str, default="1",
        help="The number of cores to reserve for processing high priority messages on each host")

    try:
        args = parser.parse_args()
    except:
        print >> sys.stderr, "ERROR: failed to parse command line options"
        sys.exit(2)

    argsMap = {'clientThreadsPerHost': args.clientThreadsPerHost, 
               'serverThreadsPerHost': args.serverThreadsPerHost, 
               'serverProcessingTime': args.serverProcessingTime, 
               'serverNetLoad': args.serverNetLoad,
               'clientHPReqRate': args.clientHPReqRate, 
               'clientLPReqRate': args.clientLPReqRate, 
               'clientReqGrpSize': args.clientReqGrpSize, 
               'coresForHPThreads': args.coresForHPThreads}
    run_sims_range(args, argsMap)
    



if __name__ == "__main__":
    main()

